import tkinter as tk
m=tk.Tk()
m.title('Travelling Salesman Problem')
c=tk.Message(m,text='Select Source City')
def ff():
    m=tk.Tk()
    m.title('Travelling Salesman Problem')
    def gg():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 61 km')
        b.pack()
        m.mainloop()
    def zz():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 80 km')
        b.pack()
        m.mainloop()
    def mm():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 149 km')
        b.pack()
        m.mainloop()
    def nn():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 154 km')
        b.pack()
        m.mainloop()    
    v=tk.Message(m,text='Select Destination city')
    b=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Ludhiana',bd=5,command=gg)
    d=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Amritsar   ',bd=5,command=zz)
    f=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Chandigarh ',bd=5,command=mm)
    g=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Patiala    ',bd=5,command=nn)
    v.grid()
    b.grid()
    d.grid()
    f.grid()
    g.grid()
    m.mainloop()
b=tk.Button(m,height=5,width=40,foreground='lightgreen',text='Jalandhar  ',bd=5,font=('helvetica'),command=ff)
def cc():
    m=tk.Tk()
    m.title('Travelling Salesman Problem')
    def dd():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 61 km')
        b.pack()
        m.mainloop()
    def ee():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 140 km')
        b.pack()
        m.mainloop()
    def hh():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 106 km')
        b.pack()
        m.mainloop()
    def ii():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 93 km')
        b.pack()
        m.mainloop()    
    v=tk.Message(m,text='Select Destination city')
    b=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Jalandhar',bd=5,command=dd)
    d=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Amritsar   ',bd=5,command=ee)
    f=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Chandigarh ',bd=5,command=hh)
    g=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',text='Patiala    ',bd=5,command=ii)
    v.grid()
    b.grid()
    d.grid()
    f.grid()
    g.grid()
    m.mainloop()
e=tk.Button(m,activeforeground='aqua',height=5,width=40,text='Ludhiana   ',bd=5,font=('helvetica'),command=cc)
def kk():
    m=tk.Tk()
    m.title('Travelling Salesman Problem')
    def ll():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 106 km')
        b.pack()
        m.mainloop()
    def oo():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 229 km')
        b.pack()
        m.mainloop()
    def pp():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 149 km')
        b.pack()
        m.mainloop()
    def qq():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 75 km')
        b.pack()
        m.mainloop()    
    v=tk.Message(m,text='Select Destination city')
    b=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Ludhiana',command=ll)
    d=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Amritsar   ',command=oo)
    f=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Jalandhar ',command=pp)
    g=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Patiala    ',command=qq)
    v.grid()
    b.grid()
    d.grid()
    f.grid()
    g.grid()
    m.mainloop()
d=tk.Button(m,height=5,width=40,font=('helvetics'),text='Chandigarh',bd=5,foreground='green',command=kk)
def rr():
    m=tk.Tk()
    m.title('Travelling Salesman Problem')
    def ss():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 140 km')
        b.pack()
        m.mainloop()
    def tt():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 80 km')
        b.pack()
        m.mainloop()
    def uu():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 229 km')
        b.pack()
        m.mainloop()
    def vv():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 75 km')
        b.pack()
        m.mainloop()    
    v=tk.Message(m,text='Select Destination city')
    b=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Ludhiana',command=ss)
    d=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Jalandhar   ',command=tt)
    f=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Chandigarh ',command=uu)
    g=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Patiala    ',command=vv)
    v.grid()
    b.grid()
    d.grid()
    f.grid()
    g.grid()
    m.mainloop()
f=tk.Button(m,height=5,width=40,font=('helvetica'),text='Amritsar',bd=5,command=rr)
def ww():
    m=tk.Tk()
    m.title('Travelling Salesman Problem')
    def xx():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 93 km')
        b.pack()
        m.mainloop()
    def yy():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 80 km')
        b.pack()
        m.mainloop()
    def ee():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 149 km')
        b.pack()
        m.mainloop()
    def aaa():
        m=tk.Tk()
        m.title('Travelling Salesman Problem')
        b=tk.Message(m,text='Shortest distance is 154 km')
        b.pack()
        m.mainloop()    
    v=tk.Message(m,text='Select Destination city')
    b=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Ludhiana',command=xx)
    d=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Amritsar   ',command=yy)
    f=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Chandigarh ',command=ee)
    g=tk.Button(m,activeforeground='blue',height=5,width=25,foreground='green',bd=5,text='Patiala    ',command=aaa)
    v.grid()
    b.grid()
    d.grid()
    f.grid()
    g.grid()
    m.mainloop()
g=tk.Button(m,height=5,width=40,font=('helvetica'),text='Patiala    ',bd=5,command=ww)
c.grid()
b.grid()
e.grid()
d.grid()
f.grid()
g.grid()
m.mainloop()

    
